apiVersion: v1
kind: Service
metadata:
  name: producto-inventario-movil-service
  namespace: medisupply
spec:
  type: ClusterIP
  selector:
    app: producto-inventario-movil
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5005
