apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos-deployment
  namespace: medisupply
  labels:
    app: productos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productos
  template:
    metadata:
      labels:
        app: productos
    spec:
      containers:
      - name: productos
        image: 012146976167.dkr.ecr.us-east-2.amazonaws.com/productos:latest
        ports:
        - containerPort: 5008
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - |
          export DATABASE_URL="postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-service:5432/medisupply"
          export REDIS_SERVICE_URL="http://redis-service:5011"
          export MINIO_ENDPOINT="minio-service:9000"
          export MINIO_ACCESS_KEY="$(MINIO_ACCESS_KEY)"
          export MINIO_SECRET_KEY="$(MINIO_SECRET_KEY)"
          export MINIO_SECURE="False"
          python run.py
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio-secret-key
        - name: REDIS_IMPORT_CHANNEL
          value: "productos_import_csv_prod"
