apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-cache-deployment
  namespace: medisupply
  labels:
    app: worker-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-cache
  template:
    metadata:
      labels:
        app: worker-cache
    spec:
      nodeSelector:
        local-imports: "true"
      containers:
      - name: worker-cache
        image: 012146976167.dkr.ecr.us-east-2.amazonaws.com/productos:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - 'export DATABASE_URL="postgresql://postgres:${POSTGRES_PASSWORD}@postgres-service:5432/medisupply" && export REDIS_HOST="redis" && export REDIS_PORT="6379" && export REDIS_SERVICE_URL="http://redis-service:5011" && python worker.py'
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: REDIS_IMPORT_CHANNEL
            value: "productos_import_csv_prod"

        volumeMounts:
          - name: local-imports
            mountPath: /app/local_imports
      volumes:
      - name: local-imports
        hostPath:
          path: /var/local_imports
          type: DirectoryOrCreate
