apiVersion: v1
kind: Service
metadata:
  name: inventarios-service
  namespace: medisupply
  labels:
    app: inventarios
spec:
  type: ClusterIP
  selector:
    app: inventarios
  ports:
  - name: http
    port: 5009
    targetPort: 5009
    protocol: TCP
