apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: medisupply
  labels:
    app: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis-service
  ports:
  - name: http
    port: 5011
    targetPort: 5011
    protocol: TCP
