apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: medisupply
type: Opaque
stringData:
  # Credenciales de MinIO para acceso S3
  # CAMBIAR EN PRODUCCIÃ“N con valores seguros
  minio-access-key: "medisupply_access_key"
  minio-secret-key: "medisupply_secret_key_2024"
