apiVersion: v1
kind: ConfigMap
metadata:
  name: mediador-web-configmap
  namespace: medisupply
data:
  AUTH_URL: "http://auth-usuario-service:5001"
  PROVEEDORES_URL: "http://proveedores-service:5006"
  VENDEDORES_URL: "http://vendedores-service:5007"
  PRODUCTO_URL: "http://productos-service:5008"
  INVENTARIOS_URL: "http://inventarios-service:5009"
  CLIENTES_URL: "http://clientes-service:5010"
  PEDIDOS_URL: "http://pedidos-service:5012"
  LOGISTICA_URL: "http://logistica-service:5013"
  REDIS_SERVICE_URL: "http://redis-service:5011"
