apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediador-movil-deployment
  namespace: medisupply
  labels:
    app: mediador-movil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediador-movil
  template:
    metadata:
      labels:
        app: mediador-movil
    spec:
      containers:
      - name: mediador-movil
        image: 012146976167.dkr.ecr.us-east-2.amazonaws.com/mediador-movil:latest
        ports:
        - containerPort: 5004
        envFrom:
        - configMapRef:
            name: mediador-web-configmap
        imagePullPolicy: Always
