apiVersion: v1
kind: Service
metadata:
  name: mediador-movil-service
  namespace: medisupply
spec:
  type: ClusterIP
  selector:
    app: mediador-movil
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
