name: Deploy to AWS EKS - clientes-microservice

on:
  push:
    branches:
      - main
    paths:
      - 'clientes_microservice/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID_JOSE: ${{ secrets.AWS_ACCOUNT_ID_JOSE }}
      ECR_REPO: clientes_microservice
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_JOSE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_JOSE }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID_JOSE.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and push Docker image (clientes_microservice)
        run: |
          docker build -t $AWS_ACCOUNT_ID_JOSE.dkr.ecr.us-east-2.amazonaws.com/$ECR_REPO:latest ./clientes_microservice
          docker push $AWS_ACCOUNT_ID_JOSE.dkr.ecr.us-east-2.amazonaws.com/$ECR_REPO:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-2 --name medisupply-cluster-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/clientes_microservice/deployment.yaml
          kubectl apply -f kubernetes/clientes_microservice/service.yaml

      - name: Restart clientes_microservice deployment
        run: |
          kubectl rollout restart deployment clientes-microservice-deployment -n medisupply
